apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

# Centralized configuration
images:
  - name: REGISTRY_URL/PROJECT_ID/ride-sharing/api-gateway
    newName: us-west1-docker.pkg.dev/PROJECT_ID/ride-sharing/api-gateway
    newTag: latest
  - name: REGISTRY_URL/PROJECT_ID/ride-sharing/trip-service
    newName: us-west1-docker.pkg.dev/PROJECT_ID/ride-sharing/trip-service
    newTag: latest

# Resources to deploy
resources:
  - api-gateway-deployment.yaml
  - trip-service-deployment.yaml
  - app-config.yaml

# Common labels
commonLabels:
  environment: production
  managed-by: kustomize
