apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-service
  template:
    metadata:
      labels:
        app: driver-service
    spec:
      containers:
        - name: driver-service
          image: ride-sharing/driver-service
          ports:
            - containerPort: 8083 # driver-service app itself will use this port to listen for incoming requests
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: uri
---
apiVersion: v1
kind: Service
metadata:
  name: driver-service
spec:
  selector:
    app: driver-service
  ports:
    - port: 8083 # API Gateway will use this port to connect to the driver-service
      name: grpc
      targetPort: 8083 # Kube Service forwards traffic to this port on the driver-service pod
  type: ClusterIP
