apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

bases:
  - ../../base

# Image mappings (CI will update these)
images:
  - name: api-gateway
    newName: us-west1-docker.pkg.dev/PROJECT_ID/ride-sharing/api-gateway
    newTag: latest
  - name: trip-service
    newName: us-west1-docker.pkg.dev/PROJECT_ID/ride-sharing/trip-service
    newTag: latest

commonLabels:
  environment: production
  managed-by: argocd
