apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default


# Image mappings (CI will update these)
images:
- name: api-gateway
  newName: us-west1-docker.pkg.dev/ride-sharing-486323/ride-sharing/api-gateway
  newTag: 2c3b3742995423467567ff98b169acd4f4d55c90
- name: trip-service
  newName: us-west1-docker.pkg.dev/ride-sharing-486323/ride-sharing/trip-service
  newTag: 68680745de38b1df58ade180fb4ab203216c3bdb

commonLabels:
  environment: production
  managed-by: argocd
resources:
- ../../base
