apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ride-sharing-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/Mark-Vu/go-microservices-kubernetes
    targetRevision: main
    path: infra/production/k8s/overlays/production
  
  # Destination: Current cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  # Sync policy
  syncPolicy:
    automated:
      prune: true       # Delete resources not in Git
      selfHeal: true    # Auto-sync if cluster drifts
    syncOptions:
      - CreateNamespace=true
    
    # Retry strategy
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m
